$('#fieldLocationSearch').oninput=e=>{clearFieldLoc();const q=e.target.value.trim().toUpperCase().replace(/\s/g,'');const box=$('#fieldLocationResults');if(!q){box.classList.add('hidden');return}const ms=window.APARTMENT_DATA.filter(a=>a.unit.toUpperCase().includes(q)||a.building.includes(q)||a.code.toUpperCase().includes(q)).slice(0,12);box.innerHTML=ms.map(a=>`<button type="button" data-code="${esc(a.code)}"><div class="auto-code">${esc(a.code)}</div><div class="auto-address">${esc(apartmentDisplay(a))}</div></button>`).join('');box.classList.toggle('hidden',!ms.length);box.querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=window.APARTMENT_DATA.find(x=>x.code===b.dataset.code),f=$('#fieldEmergencyForm');f.elements.locationCode.value=a.code;f.elements.fullAddress.value=apartmentAddress(a);$('#fieldLocationSearch').value=a.code;$('#fieldSelectedLocation').textContent=apartmentDisplay(a);$('#fieldSelectedLocation').classList.remove('hidden');box.classList.add('hidden');fieldManual=false;$('#fieldManualLocationWrap').classList.add('hidden')})};
$('#fieldManualLocationBtn').onclick=()=>{fieldManual=!fieldManual;clearFieldLoc();$('#fieldManualLocationWrap').classList.toggle('hidden',!fieldManual)};
$('#fieldUsedVendor').onchange=e=>syncVendorPanel('field',e.target.checked);$('#fieldVendorSelect').onchange=()=>syncVendorPanel('field',$('#fieldUsedVendor').checked);
$('#fieldEmergencyForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries()),ev=makeEvent('emergency',d.date,d.in,d.out,'field');Object.assign(ev,{timeReceived:d.timeReceived||d.in,dateReceived:d.date,locationCode:d.locationCode||'',fullAddress:d.fullAddress||'',manualLocation:d.manualLocation||'',occupant:d.occupant||'',phone:d.phone||'',problem:d.problem||'Emergency',finding:d.finding||'',solution:d.solution||'',specialInstructions:d.specialInstructions||'',remarks:d.remarks||'',result:d.remarks||'',material:d.material||'',quantity:d.quantity||'',vendor:$('#fieldUsedVendor').checked?vendorValue('field'):'',vendorWork:$('#fieldUsedVendor').checked?(d.vendorWork||''):'',status:d.status||'Job Complete'});events.push(ev);save(K.events,events);learnEvent(ev);e.currentTarget.reset();e.currentTarget.elements.date.value=todayISO();$('#fieldSelectedLocation').classList.add('hidden');$('#fieldManualLocationWrap').classList.add('hidden');$('#fieldUsedVendor').checked=false;populateVendorSelect($('#fieldVendorSelect'),'');$('#fieldVendorManual').value='';syncVendorPanel('field',false);toast('Emergency saved. It will appear on the matching Payroll day and will not be deleted when Humanity is imported.');renderRequests();renderSummary()};
// Event editor / requests

function populateEventTypeSelect(sel,cur){sel.innerHTML=typeOptions(cur)}
function vendorNames(){return [...new Set(vendors.filter(v=>v.active!==false).map(v=>v.company).filter(Boolean))].sort()}
function populateVendorSelect(sel,cur=''){const names=vendorNames();sel.innerHTML='<option value="">— Select —</option>'+names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('')+'<option value="__manual__">+ Enter Manually</option>';if(cur&&names.includes(cur))sel.value=cur;else if(cur)sel.value='__manual__';else sel.value=''}
function syncVendorPanel(prefix,show){const panel=$(`#${prefix}VendorPanel`),sel=$(`#${prefix}VendorSelect`),manualWrap=$(`#${prefix}VendorManualWrap`);panel?.classList.toggle('hidden',!show);if(show&&sel)manualWrap?.classList.toggle('hidden',sel.value!=='__manual__')}
function vendorValue(prefix){const sel=$(`#${prefix}VendorSelect`);if(!sel)return'';return sel.value==='__manual__'?($(`#${prefix}VendorManual`)?.value||'').trim():sel.value}
function clearEditLocationSelection(){const f=$('#eventEditorForm');if(f?.elements.fullAddress)f.elements.fullAddress.value='';const box=$('#editLocationResults');if(box)box.classList.add('hidden');const sel=$('#editSelectedLocation');if(sel)sel.classList.add('hidden')}
function renderEditLocationMatches(q){const box=$('#editLocationResults');if(!box)return;const needle=(q||'').trim().toUpperCase().replace(/\s/g,'');if(!needle||needle==='POOL'){box.classList.add('hidden');return}const ms=window.APARTMENT_DATA.filter(a=>a.unit.toUpperCase().includes(needle)||a.building.includes(needle)||a.code.toUpperCase().includes(needle)).slice(0,12);box.innerHTML=ms.map(a=>`<button type="button" data-code="${esc(a.code)}"><div class="auto-code">${esc(a.code)}</div><div class="auto-address">${esc(apartmentDisplay(a))}</div></button>`).join('');box.classList.toggle('hidden',!ms.length);box.querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=window.APARTMENT_DATA.find(x=>x.code===b.dataset.code),f=$('#eventEditorForm');if(!a||!f)return;f.elements.locationCode.value=a.code;f.elements.fullAddress.value=apartmentAddress(a);$('#editLocationSearch').value=a.code;const sel=$('#editSelectedLocation');sel.textContent=apartmentDisplay(a);sel.classList.remove('hidden');box.classList.add('hidden')})}
$('#editLocationSearch').oninput=e=>{const f=$('#eventEditorForm');if(f.elements.type.value==='pool_open'||f.elements.type.value==='pool_close'){return}clearEditLocationSelection();renderEditLocationMatches(e.target.value)};
function openEventEditor(id){const e=events.find(x=>x.id===id);if(!e)return;editingEventId=id;const f=$('#eventEditorForm');populateEventTypeSelect($('#editEventType'),e.type);for(const n of ['date','in','out','dateReceived','timeReceived','locationCode','fullAddress','occupant','phone','problem','finding','solution','material','quantity','vendorWork','specialInstructions','status','worker'])if(f.elements[n])f.elements[n].value=e[n]||'';f.elements.remarks.value=e.remarks||e.result||'';f.elements.type.value=e.type;if(e.type==='pool_open'||e.type==='pool_close'){f.elements.locationCode.value='POOL';f.elements.fullAddress.value=poolAreaAddress()}const sel=$('#editSelectedLocation');if(f.elements.fullAddress.value){sel.textContent=f.elements.fullAddress.value;sel.classList.remove('hidden')}else sel.classList.add('hidden');$('#editLocationResults').classList.add('hidden');const used=!!(e.vendor||e.vendorWork);$('#editUsedVendor').checked=used;populateVendorSelect($('#editVendorSelect'),e.vendor||'');$('#editVendorManual').value=e.vendor&&!vendorNames().includes(e.vendor)?e.vendor:'';syncVendorPanel('edit',used);applyPoolTemplateToEditor(false);$('#eventEditorMeta').textContent=`${eventTypeLabel(e.type)} · ${e.source} · ${eventLinked(e)?'Linked to TIME CARD':'Payroll reconciliation pending'}`;openModal('eventEditorModal')}
$('#editUsedVendor').onchange=e=>syncVendorPanel('edit',e.target.checked);$('#editVendorSelect').onchange=()=>syncVendorPanel('edit',$('#editUsedVendor').checked);$('#editEventType').onchange=()=>{const t=$('#editEventType').value;if(t==='pool_open'||t==='pool_close')applyPoolTemplateToEditor(true);else{$('#poolTemplateNote').classList.add('hidden');$('#editSelectedLocation').classList.add('hidden')}};$('#restorePoolTemplateBtn').onclick=()=>applyPoolTemplateToEditor(true);
$('#eventEditorForm').onsubmit=e=>{e.preventDefault();const ev=events.find(x=>x.id===editingEventId);if(!ev)return;const savedId=ev.id,d=Object.fromEntries(new FormData(e.currentTarget).entries());const oldType=ev.type;Object.assign(ev,d);ev.vendor=$('#editUsedVendor').checked?vendorValue('edit'):'';if(!$('#editUsedVendor').checked)ev.vendorWork='';ev.result=ev.remarks||'';applyTypeDefaults(ev,ev.type,oldType);save(K.events,events);learnEvent(ev);closeModal('eventEditorModal');renderAll();previewRequest(savedId);toast(settings.language==='es'?'Maintenance Request guardado. Vista previa actualizada.':'Maintenance Request saved. Preview updated.');};
async function deleteEvent(id){const e=events.find(x=>x.id===id);if(!e)return;if(!await appConfirm(`Delete ${eventLabel(e)}? This removes its Maintenance Request and On-Call Summary row, but does NOT delete payroll hours.`,'Delete Event'))return;events=events.filter(x=>x.id!==id);save(K.events,events);renderAll()}
function needsDetails(e){return e.type==='emergency'&&(/Details Pending/i.test(e.problem)||!locationLabel(e))}
function renderRequests(){
  const list=$('#requestList'),es=eventsPeriod(),start=periodFolioStart();
  const input=$('#folioStartInput'),status=$('#folioStatus');
  if(input)input.value=start||'';
  if(status){
    const assigned=es.filter(e=>e.requestNumber).length;
    status.textContent=start?`Starting folio ${formatFolio(start)} · ${assigned}/${es.length} requests currently numbered.`:'No starting folio configured for this pay period.';
  }
  if(!es.length){list.innerHTML='<div class="muted">No reportable events saved for this pay period.</div>';return}
  list.innerHTML=es.map(e=>`<div class="item"><div class="row between wrap gap"><div><div class="item-title">${e.requestNumber?`<span class="badge">Folio ${esc(e.requestNumber)}</span> `:''}${esc(fmtDate(e.date))} · ${esc(eventLabel(e))}</div><div class="item-meta">${clock(e.in)}${e.out?'–'+clock(e.out):''} · ${esc(locationLabel(e)||'Location pending')}</div><div class="badges"><span class="badge ${eventLinked(e)?'ok':'warn'}">${eventLinked(e)?'Linked to TIME CARD':'Payroll reconciliation pending'}</span><span class="badge">${esc(e.source)}</span>${needsDetails(e)?'<span class="badge red">Needs Details</span>':''}</div></div><div class="row gap wrap"><button class="secondary edit-event" data-id="${e.id}">Edit</button><button class="secondary preview-request" data-id="${e.id}">Preview</button><button class="dangerbtn delete-event" data-id="${e.id}">Delete</button></div></div></div>`).join('');
  $$('.edit-event').forEach(b=>b.onclick=()=>openEventEditor(b.dataset.id));
  $$('.delete-event').forEach(b=>b.onclick=()=>deleteEvent(b.dataset.id));
  $$('.preview-request').forEach(b=>b.onclick=()=>previewRequest(b.dataset.id))
}
$('#assignFoliosBtn').onclick=async()=>{
  const raw=$('#folioStartInput').value.trim(),n=parseInt(raw,10);
  if(!Number.isFinite(n)||n<1)return toast('Enter a valid starting folio number.');
  if(eventsPeriod().some(e=>e.requestNumber)){
    if(!await appConfirm(`Reassign all Maintenance Request folios for this pay period beginning with ${formatFolio(n)}?`,'Reassign Folios'))return;
  }
  assignPeriodFolios(n);renderRequests();toast(`Folios assigned beginning with ${formatFolio(n)}.`);
};
