function renderVendors(){const q=($('#vendorSearch').value||'').toLowerCase(),list=$('#vendorList'),vs=vendors.filter(v=>v.active!==false&&[v.company,v.contact,v.specialty,v.phone].join(' ').toLowerCase().includes(q));list.innerHTML=vs.map(v=>`<div class="item"><div class="item-title">${esc(v.company)}</div><div class="item-meta">${esc(v.specialty)} · ${esc(v.contact)} · ${esc(v.phone)}</div></div>`).join('')}
$('#vendorSearch').oninput=renderVendors;
$('#exportDataBtn').onclick=()=>{const data={version:'0.5.8',settings,currentPeriodStart,payrollStore,snapshots,events,problems,folioStarts,localKnowledge,vendors};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='oncall-maintenance-v0.5.8-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#importDataFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(d.version&&!String(d.version).startsWith('0.4')&&!String(d.version).startsWith('0.5'))throw new Error('This version imports v0.4 or v0.5 backups.');settings=d.settings?{...settings,...d.settings}:settings;currentPeriodStart=d.currentPeriodStart||currentPeriodStart;if(d.payrollStore)payrollStore=d.payrollStore;if(d.snapshots)snapshots=d.snapshots;if(Array.isArray(d.events))events=d.events;if(Array.isArray(d.problems))problems=d.problems;if(d.folioStarts)folioStarts=d.folioStarts;if(Array.isArray(d.localKnowledge))localKnowledge=d.localKnowledge;if(Array.isArray(d.vendors))vendors=d.vendors;save(K.settings,settings);save(K.period,currentPeriodStart);save(K.payroll,payrollStore);save(K.snap,snapshots);save(K.events,events);save(K.problems,problems);save(K.folios,folioStarts);save(K.knowledge,localKnowledge);save(K.vendors,vendors);const learned=learnFromExistingEvents();applyLanguage();renderAll();toast(`Backup imported.${learned?` ${learned} report(s) added to local Knowledge Base.`:''}`)}catch(err){toast('Import failed: '+err.message)}finally{e.target.value=''}};
$('#importSetupFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(d.kind!=='oncall-local-setup')throw new Error('Not an On-Call Local Setup package.');if(d.settings)settings={...settings,...d.settings};if(Array.isArray(d.vendors))vendors=d.vendors;if(Array.isArray(d.localKnowledge)){const known=new Set(localKnowledge.map(knowledgeKey));for(const k of d.localKnowledge){if(!known.has(knowledgeKey(k)))localKnowledge.push(k)}}save(K.settings,settings);save(K.vendors,vendors);save(K.knowledge,localKnowledge);applyLanguage();renderAll();toast('Local setup imported. Property profile and vendor list are now stored only in this browser/device.')}catch(err){toast('Setup import failed: '+err.message)}finally{e.target.value=''}};
$('#resetAppBtn').onclick=async()=>{if(!await appConfirm('Delete ALL local On-Call data in this browser? This cannot be undone unless you exported a backup.','Reset Local Data'))return;Object.values(K).forEach(k=>localStorage.removeItem(k));location.reload()};
function renderAll(){updateDashboard();renderSettings();renderPayroll();renderSummary();renderRequests();refreshProblems();renderKnowledge();renderVendors();if($('#fieldVendorSelect')&&!$('#fieldVendorSelect').options.length)populateVendorSelect($('#fieldVendorSelect'),'');$('#fieldEmergencyForm').elements.date.value=$('#fieldEmergencyForm').elements.date.value||todayISO();$('#hoursModeTitle').textContent=hoursMode==='manual'?(settings.language==='es'?'Ingreso Manual':'Manual Entry'):tr('reviewHours');$('#hoursModeHelp').textContent=hoursMode==='manual'?(settings.language==='es'?'Las horas capturadas manualmente como base se mantienen negras hasta que las corrijas en Review.':'Manual base hours remain black until changed in Review.'):(settings.language==='es'?'Cambios o bloques nuevos en Review se marcan en rojo para la manager.':'Changes or new blocks in Review are marked red for the manager.')}

let deferredInstallPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;const b=$('#installAppBtn');if(b)b.classList.remove('hidden')});
$('#installAppBtn').onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installAppBtn').classList.add('hidden');return}const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);toast(ios?'On iPhone/iPad: Safari → Share → Add to Home Screen.':'Use your browser menu → Install app / Add to Home screen.')};
window.addEventListener('appinstalled',()=>{const b=$('#installAppBtn');if(b)b.classList.add('hidden');toast('On-Call Maintenance Assistant installed.')});
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./service-worker.js',{updateViaCache:'none'});await reg.update()}catch(e){}});

applyLanguage();renderAll();
